apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-app

  strategy:
    blueGreen:
      activeService: demo-app-stable
      previewService: demo-app-preview
      autoPromotionEnabled: false

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 275839157288.dkr.ecr.ap-south-2.amazonaws.com/k8s-gitops-app:962a7ecaa1642151a18129524b0186af748a7808
          ports:
            - containerPort: 5000
