apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-app

  strategy:
    blueGreen:
      activeService: demo-app-stable
      previewService: demo-app-preview
      autoPromotionEnabled: false

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 275839157288.dkr.ecr.ap-south-2.amazonaws.com/k8s-gitops-app:52df64c7f36061cfab551bbc24c3aa8e55cbb27b
          ports:
            - containerPort: 5000
