apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 275839157288.dkr.ecr.ap-south-2.amazonaws.com/k8s-gitops-app:962a7ecaa1642151a18129524b0186af748a7808
          ports:
            - containerPort: 80
